#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH=~/bin:/usr/local/bin:/usr/local/opt/mongodb@3.6/bin:/Users/winterhalder/bitHeads/Projects/brainCloud/braincloud-server/Development/database:$PATH

export GOROOT=/usr/local/opt/go/libexec
#export GOPATH=~/bitHeads/Projects/statsims/go-workspace
export GOPATH=~/bitheads/Projects/go-workspace
export GOBIN=$GOPATH/bin

export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:~/boxfuse

# Configure bc-tools
export BCTOOLSDIR=~/bitheads/projects/braincloud/bc-tools
. $BCTOOLSDIR/_bc-set-env.sh

# Configure bc-tools source directory (optional - devs only)
export BCSERVERDIR=~/bitheads/projects/braincloud/braincloud-server
