#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Update this (I guess?)
alias updatezprezto='git pull & git submodule update --init --recursive'

# brainCloud aliases
#. $BCTOOLSDIR/bc-aliases.sh
test -e "${BCTOOLSDIR}/bc-aliases.sh" && source "${BCTOOLSDIR}/bc-aliases.sh"

# My custom aliases
test -e "${HOME}/Dropbox/System/zsh/.phw-aliases.sh" && source "${HOME}/Dropbox/System/zsh/.phw-aliases.sh"

dkEnv() {
    eval $(docker-machine env $1)
}

tt () {
    DISABLE_AUTO_TITLE="true"
    echo -e "\033];$@\007"
}
