#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Update this (I guess?)
alias updatezprezto='git pull & git submodule update --init --recursive'

# brainCloud aliases
#. $BCTOOLSDIR/bc-aliases.sh
test -e "${BCTOOLSDIR}/bc-aliases.sh" && source "${BCTOOLSDIR}/bc-aliases.sh"

# My custom aliases
test -e "${HOME}/Dropbox/System/zsh/.phw-aliases.sh" && source "${HOME}/Dropbox/System/zsh/.phw-aliases.sh"

dkEnv() {
    eval $(docker-machine env $1)
}

tt () {
    DISABLE_AUTO_TITLE="true"
    echo -e "\033];$@\007"
}

# For Roger - to quickly (and completely) switch prompts. (Temporary)
changeprompt() {
  prompt $1
  setopt prompt_subst
  echo ""
  echo "vvv This is $1 vvv"
}

revertprompt() {
  prompt garrett
  setopt prompt_subst
  echo "Ah.... back to garrett"
}

# Load rbenv automatically by appending
# the following to ~/.zshrc:

eval "$(rbenv init -)"

# Source JENV to control JAVA environment. Be careful, this seems to clear JAVA_HOME
# Which is why we explicitely set it again shortly afterwards...
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
#echo $PATH

# Set JAVA_HOME vased on jenv
export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`"
alias jenv_set_java_home='export JAVA_HOME="$HOME/.jenv/versions/`jenv version-name`"'

# Node10 in path for Talespin
export PATH="/usr/local/opt/node@10/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK
if [ -f '/Users/winterhalder/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/winterhalder/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/winterhalder/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/winterhalder/google-cloud-sdk/completion.zsh.inc'; fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
