#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Custom aliases
alias updatezprezto='git pull & git submodule update --init --recursive'

alias keys='cd /Users/winterhalder/bitHeads/Projects/brainCloud/braincloud-server/References/keys'

# brainCloud
alias prodsm1='ssh -A ec2-user@ec2-35-171-2-145.compute-1.amazonaws.com'
alias prodsm2='ssh -A ec2-user@ec2-52-91-81-41.compute-1.amazonaws.com'
alias intsm2='ssh -A ec2-user@ec2-52-32-168-105.us-west-2.compute.amazonaws.com'
alias intsm1='ssh -A ec2-user@ec2-52-10-202-5.us-west-2.compute.amazonaws.com'
alias emptydb='ssh -A ec2-user@emptydb.braincloudservers.com'

# bitHead infrastructure
alias jenkins='ssh buildmaster@207.181.118.33'

# customer servers
alias simengine2='ssh -A ec2-user@ec2-13-57-16-116.us-west-1.compute.amazonaws.com'

# ssh to home
alias darkmac='ssh -p 22 winterhalder@DarkMac.38605281.members.btmm.icloud.com'

dkEnv() {
    eval $(docker-machine env $1)
}

. $BCTOOLSDIR/bc-aliases.sh

echo Re-registering ssh keys...
ssh-add -K ~/.ssh/id_rsa 2>/dev/null
ssh-add -K /Users/winterhalder/bitHeads/Projects/brainCloud/braincloud-server/References/keys/bhkey2013.pem 2>/dev/null
ssh-add -K /Users/winterhalder/bitHeads/Projects/brainCloud/braincloud-server/References/keys/bhkeyOregon.pem 2>/dev/null
ssh-add -K /Users/winterhalder/bitHeads/Projects/brainCloud/braincloud-server/References/keys/bhNorthCalifKey.pem 2>/dev/null
ssh-add -K /Users/winterhalder/bitHeads/Projects/brainCloud/braincloud-server/References/keys/bitHeads_subor_US_West.pem 2>/dev/null

tt () {
    DISABLE_AUTO_TITLE="true"
    echo -e "\033];$@\007"
}
