#
# Executes commands at the start of an interactive session.
#
# Customized for braincloud deployment servers
#

# Configure bc-tools. Add to .bashrc or .zshrc (before sourcing of Prezto)
if [ -d ~/bc-tools ]; then
  export BCTOOLSDIR=~/bc-tools
  . $BCTOOLSDIR/_bc-set-env.sh
  ~/bc-tools/bc-safe-ops.sh info # Only for deployment boxes. Comment or remove this line if its your workstation
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Iterm shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Custom aliases
alias updatezprezto='cd ~/.zprezto; git pull & git submodule update --init --recursive'

# For Roger - to quickly (and completely) switch prompts. (Temporary)
changeprompt() {
  prompt $1
  setopt prompt_subst
  echo ""
  echo "vvv This is $1 vvv"
}

revertprompt() {
  prompt garrett
  setopt prompt_subst
  echo "Ah.... back to garrett"
}

# Customize to your needs...

